# Used to resume training after the B6 (1024 x 1024, 30 epochs) + (1280 x 1280, 15 epochs)
batch_size: 6
image_size:
- 1356
- 1356
max_epochs: 10
model_name: tf_efficientnet_b6_ns
out_indices:
- 3
- 4
n_splits: -1
pseudo_label: pseudo_labels/round2.csv
pseudo_conf_threshold: 0.6


lr_backbone: 0.8e-5
lr_head: 0.3e-4