# Used to resume training after the B6 (1024 x 1024, 30 epochs)
batch_size: 6
image_size:
- 1024
- 1024
max_epochs: 15
model_name: tf_efficientnet_b6_ns
out_indices:
- 3
- 4
n_splits: -1
pseudo_label: pseudo_labels/round2.csv
pseudo_conf_threshold: 0.6


lr_backbone: 2.8e-5
lr_head: 2.3e-4